DROP TABLE IF EXISTS cocktails CASCADE;
DROP TABLE IF EXISTS ingredients CASCADE;
DROP TABLE IF EXISTS tags CASCADE;
DROP TABLE IF EXISTS ricepts CASCADE;
DROP TABLE IF EXISTS cocktail_tag CASCADE;


